### ISSUE TITLE
Installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by cscd98** [danielgtaylor/ladon#1]
I've installed nodejs from the latest repo:

```
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install python-software-properties python g++ make nodejs 
```

Then ladon:

```
sudo npm install -g ladon
npm http GET https://registry.npmjs.org/ladon
npm http 304 https://registry.npmjs.org/ladon
npm http GET https://registry.npmjs.org/yargs
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/yargs
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/minimist
/usr/bin/ladon -> /usr/lib/node_modules/ladon/ladon.js
ladon@1.0.4 /usr/lib/node_modules/ladon
├── mkdirp@0.3.5
├── async@0.6.2
├── glob@3.2.9 (inherits@2.0.1, minimatch@0.2.14)
└── yargs@1.2.1 (minimist@0.0.10)
```

ladon outputs nothing?

**Comment by danielgtaylor** [comment]
@craigcarnell it looks like you've successfully installed ladon. Have you tried running it? For example:

``` bash
ladon "**/*" -- echo RELPATH
```

You should see a bunch of output for all the files and directories in the current directory. You can stop it via `ctrl+c`.

**Comment by cscd98** [comment]
@danielgtaylor Nothing gets output which is the weird thing

**Comment by danielgtaylor** [comment]
@craigcarnell do you have any files in the directory from which you are running the command? What version of Node.js are you using? Is there anything else that's interesting about your setup? Network shares?

**Comment by cscd98** [comment]
nodejs -v
v0.10.28

ccarnell@web:~$ vi test
ccarnell@web:~$ ls
src  test  tmp
ccarnell@web:~$ ladon "*_/_" -- echo RELPATH

Nothing particularly it's more or less a fresh cloud server.

**Comment by danielgtaylor** [comment]
Very strange. Here is my test on an Ubuntu VM on Digital Ocean:

``` bash
$ lsb_release -i -r
Distributor ID: Ubuntu
Release:        14.04

$ node --version
v0.10.28

$ mkdir -p test/dir1/dir2
$ touch test/foo.txt test/dir1/bar.jpg test/dir1/dir2/baz.pdf
$ cd test
$ ladon "**/*" -- echo RELPATH
dir1
dir1/bar.jpg
dir1/dir2
dir1/dir2/baz.pdf
foo.txt
```

I'm not sure what the problem might be for you. Are you using a shell that isn't bash? Maybe it could be treating the "*_/_" as something special?

**Comment by cscd98** [comment]
Seems to be an issue with node, I uninstalled and re-installed and now it outputs. Thanks for your help.
